server:
  port: 8101

spring:
  application:
    name: REGISTRY-1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    prefer-same-zone-eureka: true
    service-url:
      zone-1: http://eureka.local.com:8101/eureka/
      zone-2: http://eureka.local.com:8102/eureka/
      zone-3: http://eureka.local.com:8103/eureka/
    region: China
    availability-zones:
      China: zone-1,zone-2,zone-3
  instance:
    hostname: eureka.local.com


