server:
  port: 8301

spring:
  application:
    name: client-service

eureka:
  client:
    service-url:
      defaultZone: http://eureka.local.com:8101/eureka/,http://eureka.local.com:8102/eureka/,http://eureka.local.com:8103/eureka/
    region: CN


